"""change expense amount to numeric

Revision ID: 196344202908
Revises: 6cfcea0a30bd
Create Date: 2026-06-24 22:21:01.714583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '196344202908'
down_revision: Union[str, Sequence[str], None] = '6cfcea0a30bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budgets', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False,
                postgresql_using="amount::numeric(10,2)")
    op.drop_index(op.f('ix_budget_id'), table_name='budgets')
    op.create_index(op.f('ix_budgets_id'), 'budgets', ['id'], unique=False)
    op.alter_column('expenses', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False,
                postgresql_using="amount::numeric(10,2)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_index(op.f('ix_budgets_id'), table_name='budgets')
    op.create_index(op.f('ix_budget_id'), 'budgets', ['id'], unique=False)
    op.alter_column('budgets', 'amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
